import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";

export type ExploreLocation = {
  img: string;
  location: string;
  distance: string;
};

export type Card = {
  img: string;
  title: string;
};

type HomeProps = {
  exploreData: ExploreLocation[];
  cardsData: Card[];
};

export default function Home({ exploreData, cardsData }: HomeProps) {
  return (
    <div className="">
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-3xl font-semibold pb-5">Explore Nearby</h2>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map((ed) => (
              <SmallCard key={ed.img} location={ed} />
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-3xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map((cd) => (
              <MediumCard key={cd.img} card={cd} />
            ))}
          </div>
        </section>

        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Whishlists curated by Airbnb."
          buttonText="Get Inspired"
        />
      </main>

      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (r) => r.json()
  );

  const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").then((r) =>
    r.json()
  );

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
